@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.confluence.terra_furniture.common.block.crafting;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;