name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: "gradle"

      - name: Generate assets
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: runData -Pdev=false

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -Pdev=false

      - name: Make scripts executable
        run: chmod +x .github/workflows/scripts/*.sh

      - name: Extract mod_version and check if tag exists
        id: version
        run: .github/workflows/scripts/extract_version.sh

      # Official release (only master/main branch)
      - name: Create official release if not already published
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && steps.version.outputs.skip_release == 'false'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: release-${{ steps.version.outputs.mod_version }}
          prerelease: false
          title: "TerraFurniture Build ${{ steps.version.outputs.mod_version }}"
          files: ./build/libs/*.jar
          body: |
            ### Changes since last version
            ${{ steps.version.outputs.changelog }}

      # Latest build (master/main/test)
      - name: Always update latest build
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: latest-build
          prerelease: true
          title: "TerraFurniture Latest Build(TestOnly)"
          files: ./build/libs/*.jar
